-- +goose Up
-- +goose StatementBegin
-- One-off: the months migrated from the retiring `fin` service (PRD D91, §V6-12).
-- Generated by gen_seed.py from fin's live GET /months; 15 rows, 2025-06 … 2026-08.
--
-- ids and timestamps are PRESERVED verbatim so a row stays traceable to fin.
-- created_by is NULL: fin recorded no actor. Timestamps keep fin's nanosecond
-- RFC3339 precision rather than home's millisecond form — provenance beats
-- cosmetic consistency, and finance orders by `month`, never by timestamp.
--
-- INSERT OR IGNORE against ux_finance_months_month: applying this to a database
-- that already holds the months is a no-op, not a duplicate-key failure.
--
-- THIS FILE BELONGS TO THE SEPARATE `finance/seed` MIGRATION SOURCE (block 09900),
-- which the server entrypoint includes and `testsupport` MUST NOT (PRD D91).
INSERT OR IGNORE INTO finance_months
  (id, month, income_kaja, income_andy, rate_personal, rate_operational, rate_fun, rate_nofun, created_by, created_at, updated_at)
VALUES
  ('019f4bbf-5396-72b0-8cd7-c2dbc21e975c', '2025-06', 59415, 46698, 20, 60, 10, 10, NULL, '2026-07-10T11:17:37.814388567Z', '2026-07-10T11:17:37.814388567Z'),
  ('019f4bbf-f19a-72b0-9c70-7b936618143d', '2025-07', 60006, 46168, 20, 60, 10, 10, NULL, '2026-07-10T11:18:18.266229145Z', '2026-07-10T11:18:18.266229145Z'),
  ('019f4bc0-4f52-72b0-9596-f6eb7761ee57', '2025-08', 72037, 53047, 20, 60, 10, 10, NULL, '2026-07-10T11:18:42.258914372Z', '2026-07-10T11:18:42.258914372Z'),
  ('019f4bc0-c547-72b0-983b-85b12d50e634', '2025-09', 105161, 78738, 20, 60, 10, 10, NULL, '2026-07-10T11:19:12.455872687Z', '2026-07-10T11:19:12.455872687Z'),
  ('019f4bc1-4254-72b0-92a6-7af522218a9e', '2025-10', 60052, 48624, 20, 60, 10, 10, NULL, '2026-07-10T11:19:44.468325282Z', '2026-07-10T11:19:44.468325282Z'),
  ('019f4bc1-ce4a-72b0-a17d-791a0eace5c0', '2025-11', 64279, 46278, 20, 60, 10, 10, NULL, '2026-07-10T11:20:20.298222354Z', '2026-07-10T11:20:20.298222354Z'),
  ('019f4bc2-2f0b-72b0-b885-487e8b804742', '2025-12', 106046, 76189, 20, 60, 10, 10, NULL, '2026-07-10T11:20:45.067719488Z', '2026-07-10T11:20:45.067719488Z'),
  ('019f4bc2-8d84-72b0-a4a6-6d032809711c', '2026-01', 70703, 49161, 20, 60, 10, 10, NULL, '2026-07-10T11:21:09.252025715Z', '2026-07-10T11:21:09.252025715Z'),
  ('019f4bc2-e6d9-72b0-9a61-f2a46a1d6281', '2026-02', 72499, 53630, 20, 60, 10, 10, NULL, '2026-07-10T11:21:32.121178032Z', '2026-07-10T11:21:32.121178032Z'),
  ('019f4bc3-3bdc-72b0-b62a-96173d560256', '2026-03', 92158, 66209, 20, 60, 10, 10, NULL, '2026-07-10T11:21:53.884850931Z', '2026-07-10T11:21:53.884850931Z'),
  ('019f4bc3-9213-72b0-9dd1-0e034c28a229', '2026-04', 72276, 50717, 20, 60, 10, 10, NULL, '2026-07-10T11:22:15.955576681Z', '2026-07-10T11:22:15.955576681Z'),
  ('019f4bc3-f2f0-72b0-887b-fa1c76f177b6', '2026-05', 73087, 50540, 20, 60, 10, 10, NULL, '2026-07-10T11:22:40.752925578Z', '2026-07-10T11:22:40.752925578Z'),
  ('019f4bc4-460c-72b0-bad0-36c0a83f4a7d', '2026-06', 92300, 63652, 20, 60, 10, 10, NULL, '2026-07-10T11:23:02.028037092Z', '2026-07-10T11:23:02.028037092Z'),
  ('019f4ba9-3051-72b0-85e6-93292865b1cc', '2026-07', 67795, 51384, 20, 60, 10, 10, NULL, '2026-07-10T10:53:26.993064085Z', '2026-07-10T10:58:28.089845548Z'),
  ('019ff047-eddb-735f-90c7-ea727580705f', '2026-08', 67418, 52299, 20, 60, 10, 10, NULL, '2026-08-11T10:04:33.627222637Z', '2026-08-11T10:04:33.627222637Z');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- Deliberately empty. This migration carries the only copy of fin's history that
-- lives in home; deleting rows on a Down would be a data-loss footgun, and the
-- schema migration's own Down already drops the table.
SELECT 1;
-- +goose StatementEnd

