#!/usr/bin/env python3
"""
Generate home v6's one-off finance seed migration from `fin`'s live export.

    python3 gen_seed.py fin-months-export.json > 09900_finance_seed.sql

Input  : the raw JSON array from `GET https://fin.tilcer.cz/months` (PRD §V6-12 step 1).
Output : `09900_finance_seed.sql`, a Goose migration for the SEPARATE, production-only
         `finance/seed` migration source (PRD D91) — never the schema source, which
         `testsupport` also migrates.

The guard rails below FAIL THE GENERATION, not the migration. A bad row must be
caught here, at a desk, rather than at 3am in a deploy log — though the table's
rate-sum CHECK is the second net if one slips through.

Independently of the guard rails this script RE-DERIVES the split for every row with
fin's locked formula and compares it to the `split` block the live service returned.
That comparison is the whole reason the export must keep its `split` (PRD D97): it is
the only check that catches a formula transcribed wrong, and running it here means it
has already passed before a line of Go is written.
"""
import json
import math
import re
import sys

MONTH_RE = re.compile(r"^\d{4}-(0[1-9]|1[0-2])$")


def go_round(x: float) -> int:
    """Go's math.Round: half away from zero. Python's round() is half-to-even and
    would silently disagree on exact .5 cases — the one place a re-implementation
    of this formula can go wrong without anything else looking odd."""
    return math.floor(x + 0.5) if x >= 0 else math.ceil(x - 0.5)


def compute(income_kaja: int, income_andy: int, r: dict) -> dict:
    """The LOCKED formula (PRD §V6-4 FR-F3), transcribed from fin's split.go.
    Order is the specification: personal rounds first, transfers are subtractions,
    savings round off the total, needs is the remainder."""
    total = income_kaja + income_andy
    p, f, n = r["personal"] / 100, r["fun"] / 100, r["noFun"] / 100
    pk, pa = go_round(income_kaja * p), go_round(income_andy * p)
    tk, ta = income_kaja - pk, income_andy - pa
    opr = tk + ta
    fun, nofun = go_round(total * f), go_round(total * n)
    return {
        "totalIncome": total, "personalKaja": pk, "personalAndy": pa,
        "toOperationalKaja": tk, "toOperationalAndy": ta,
        "operationalReceived": opr, "funSavings": fun, "noFunSavings": nofun,
        "needs": opr - fun - nofun,
    }


def sql_str(v: str) -> str:
    return "'" + v.replace("'", "''") + "'"


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    rows = json.load(open(sys.argv[1], encoding="utf-8"))
    if not isinstance(rows, list):
        print("FAIL: expected a JSON array (fin's GET /months returns one, unpaged)", file=sys.stderr)
        return 1

    errors, seen = [], set()
    for i, m in enumerate(rows):
        where = f"row {i} ({m.get('month', '?')})"
        r = m.get("rates") or {}
        rsum = sum(int(r.get(k, 0)) for k in ("personal", "operational", "fun", "noFun"))
        if rsum != 100:
            errors.append(f"{where}: rates sum to {rsum}, not 100")
        if any(int(r.get(k, -1)) < 0 for k in ("personal", "operational", "fun", "noFun")):
            errors.append(f"{where}: negative rate")
        for k in ("incomeKaja", "incomeAndy"):
            v = m.get(k)
            if not isinstance(v, int) or v < 0:
                errors.append(f"{where}: {k} = {v!r} is not a non-negative integer")
        if not MONTH_RE.match(m.get("month", "")):
            errors.append(f"{where}: month {m.get('month')!r} is not YYYY-MM")
        if m["month"] in seen:
            errors.append(f"{where}: duplicate month")
        seen.add(m["month"])
        if not m.get("id"):
            errors.append(f"{where}: missing id")
        # the formula check — the reason the export must keep `split`
        if "split" in m:
            got, want = compute(m["incomeKaja"], m["incomeAndy"], r), m["split"]
            for k in want:
                if got.get(k) != want[k]:
                    errors.append(f"{where}: split.{k} live={want[k]} recomputed={got[k]}")
        else:
            errors.append(f"{where}: no `split` block — re-export WITH it (PRD D97)")

    if errors:
        print("SEED GENERATION FAILED:", file=sys.stderr)
        for e in errors:
            print("  -", e, file=sys.stderr)
        return 1

    rows.sort(key=lambda m: m["month"])
    out = [
        "-- +goose Up",
        "-- +goose StatementBegin",
        "-- One-off: the months migrated from the retiring `fin` service (PRD D91, §V6-12).",
        f"-- Generated by gen_seed.py from fin's live GET /months; {len(rows)} rows, "
        f"{rows[0]['month']} … {rows[-1]['month']}.",
        "--",
        "-- ids and timestamps are PRESERVED verbatim so a row stays traceable to fin.",
        "-- created_by is NULL: fin recorded no actor. Timestamps keep fin's nanosecond",
        "-- RFC3339 precision rather than home's millisecond form — provenance beats",
        "-- cosmetic consistency, and finance orders by `month`, never by timestamp.",
        "--",
        "-- INSERT OR IGNORE against ux_finance_months_month: applying this to a database",
        "-- that already holds the months is a no-op, not a duplicate-key failure.",
        "--",
        "-- THIS FILE BELONGS TO THE SEPARATE `finance/seed` MIGRATION SOURCE (block 09900),",
        "-- which the server entrypoint includes and `testsupport` MUST NOT (PRD D91).",
        "INSERT OR IGNORE INTO finance_months",
        "  (id, month, income_kaja, income_andy, rate_personal, rate_operational, "
        "rate_fun, rate_nofun, created_by, created_at, updated_at)",
        "VALUES",
    ]
    values = []
    for m in rows:
        r = m["rates"]
        values.append(
            f"  ({sql_str(m['id'])}, {sql_str(m['month'])}, {m['incomeKaja']}, {m['incomeAndy']}, "
            f"{r['personal']}, {r['operational']}, {r['fun']}, {r['noFun']}, "
            f"NULL, {sql_str(m['createdAt'])}, {sql_str(m['updatedAt'])})"
        )
    out.append(",\n".join(values) + ";")
    out += [
        "-- +goose StatementEnd",
        "",
        "-- +goose Down",
        "-- +goose StatementBegin",
        "-- Deliberately empty. This migration carries the only copy of fin's history that",
        "-- lives in home; deleting rows on a Down would be a data-loss footgun, and the",
        "-- schema migration's own Down already drops the table.",
        "SELECT 1;",
        "-- +goose StatementEnd",
        "",
    ]
    print("\n".join(out))
    print(f"OK: {len(rows)} rows, {rows[0]['month']}…{rows[-1]['month']}, "
          f"every split re-derived and matched", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
